# Generated by Django 3.2 on 2021-04-21 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_simplecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleblogpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Visible')], default=1),
        ),
        migrations.AlterField(
            model_name='simplecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.simplecomment'),
        ),
    ]
