# Generated by Django 3.2 on 2021-04-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210421_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleblogpost',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='simplecomment',
            name='active',
        ),
        migrations.AddField(
            model_name='simplecomment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Visible')], default=1),
        ),
    ]
